name: Tests

on:
  pull_request:
    types:
       - opened
       - reopened
       - synchronize
       - ready_for_review
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - gemfiles/rails_6.1_paper_trail_12.0_kaminari.gemfile
          - gemfiles/rails_6.1_paper_trail_12.0_will_paginate.gemfile
          - gemfiles/rails_7.0_paper_trail_12.0_kaminari.gemfile
          - gemfiles/rails_7.0_paper_trail_12.0_will_paginate.gemfile
          - gemfiles/rails_7.0_paper_trail_15.0_kaminari.gemfile
          - gemfiles/rails_7.0_paper_trail_15.0_will_paginate.gemfile
          - gemfiles/rails_7.1_paper_trail_15.0_kaminari.gemfile
          - gemfiles/rails_7.1_paper_trail_15.0_will_paginate.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Generate host app for testing
        run: bundle exec rake generate_spec_app
      - name: Run RSpec
        run: |
          bundle exec rake spec
